name: MagicCarpet

main: com.Android.magiccarpet.MagicCarpet
version: 1.5
commands:
  mc:
    description: Take yourself wonder by wonder on a carpet made of glass.
    usage:
  magiccarpet:
    description: Take yourself wonder by wonder on a carpet made of glass.
    usage: