name: MagicCarpet

main: com.Android.magiccarpet.MagicCarpet
version: 1.5.2
commands:
  mc:
    description: Take yourself wonder by wonder on a carpet made of glass.
    usage:
  magiccarpet:
    description: Take yourself wonder by wonder on a carpet made of glass.
    usage:
  ml:
    description: A bright light for your carpet ride.
    usage: