name: MagicCarpet

main: com.Android.magiccarpet.MagicCarpet
version: 1.5.6
commands:
  magiccarpet:
    description: Take yourself wonder by wonder on a carpet made of glass.
    aliases: [mc]
    usage: /<command> [size]
  magiclight:
    description: A bright light for your carpet ride.
    aliases: [ml]
    usage: /<command> [ring|centre|center]
  carpetswitch:
    description: Allows the user to switch methods for going down with the carpet.
    aliases: [mcs]
    usage: /<command>
permissions:
  magiccarpet.mc:
    description: Take yourself wonder by wonder on a carpet made of glass.
    default: op
  magiccarpet.ml:
    description: Allows a bright light for your carpet ride.
    default: op
  magiccarpet.mcs:
    description: Allows the user to switch methods for going down with the carpet.
    default: op