name: MagicCarpet
main: net.digiex.magiccarpet.MagicCarpet
version: 2.2.2
url: http://dev.bukkit.org/server-mods/magiccarpet/
description: Take yourself wonder by wonder on a carpet made of glass.
database: false
load: POSTWORLD
authors: [Android, Celtic Minstrel, xzKinGzxBuRnzx]
softdepend: [WorldGuard, Vault]
commands:
  magiccarpet:
    description: Take yourself wonder by wonder on a carpet made of glass.
    aliases: [mc]
    usage: /<command> [size] [material]
    usage: /<command> give [player]
    usage: /<command> take [player]
  magiclight:
    description: A bright light for your carpet ride.
    aliases: [ml]
    usage: /<command> [material]
  carpetswitch:
    description: Allows the user to switch methods for going down with the carpet.
    aliases: [mcs]
    usage: /<command>
  magicreload:
    description: Reloads MagicCarpet.
    aliases: [mr]
    usage: /<command>
permissions:
  magiccarpet.ml:
    description: Allows a bright light for your carpet ride.
    default: op
  magiccarpet.mcs:
    description: Allows the player to switch methods for going down with the carpet.
    default: op
  magiccarpet.mr:
    description: Allows the player to reload MagicCarpet.
    default: op
  magiccarpet.mc:
    description: Take yourself wonder by wonder on a carpet made of glass.
    default: op
  magiccarpet.*:
    description: Allows access to all MagicCarpet commands.
    default: op
    children:
      magiccarpet.mc: true
      magiccarpet.ml: true
      magiccarpet.mcs: true
      magiccarpet.mr: true
