name: MagicCarpet
main: net.digiex.magiccarpet.MagicCarpet
version: 2.0.6
url: http://dev.bukkit.org/server-mods/magiccarpet/
description: "Take yourself wonder by wonder on a carpet made of glass."
database: false
startup: postworld
authors: [Android, Celtic Minstrel, xzKinGzxBuRnzx]
commands:
  magiccarpet:
    description: Take yourself wonder by wonder on a carpet made of glass.
    aliases: [mc]
    usage: /<command> [size] [material]
  magiclight:
    description: A bright light for your carpet ride.
    aliases: [ml]
    usage: /<command> [material]
  carpetswitch:
    description: Allows the user to switch methods for going down with the carpet.
    aliases: [mcs]
    usage: /<command>
  magicreload:
    description: Reloads MagicCarpet.
    aliases: [mr]
    usage: /<command>
permissions:
  magiccarpet.mc:
    description: Take yourself wonder by wonder on a carpet made of glass.
    default: op
  magiccarpet.ml:
    description: Allows a bright light for your carpet ride.
    default: op
  magiccarpet.mcs:
    description: Allows the player to switch methods for going down with the carpet.
    default: op
  magiccarpet.tp:
    description: Allows the carpet to move when teleporting while active.
    default: op
  magiccarpet.mc.3:
    description: Allows the carpet to operate at 3.
    default: op
  magiccarpet.mc.5:
    description: Allows the carpet to operate at 5.
    default: op
  magiccarpet.mc.7:
    description: Allows the carpet to operate at 7.
    default: op
  magiccarpet.mc.9:
    description: Allows the carpet to operate at 9.
    default: op
  magiccarpet.mr:
    description: Allows the player to reload MagicCarpet.
    default: op
  magiccarpet.*:
    description: Allows access to all MagicCarpet commands.
    children:
      magiccarpet.mc: true
      magiccarpet.ml: true
      magiccarpet.mcs: true
      magiccarpet.tp: true
      magiccarpet.mc.3: true
      magiccarpet.mc.5: true
      magiccarpet.mc.7: true
      magiccarpet.mc.9: true
      magiccarpet.mr: true
