name: MagicCarpet
main: net.digiex.magiccarpet.MagicCarpet
version: 2.4.6
website: http://dev.bukkit.org/server-mods/magiccarpet/
dev-url: http://dev.bukkit.org/server-mods/magiccarpet/
description: Take yourself wonder by wonder on a carpet made of glass.
database: false
load: POSTWORLD
authors: [Android, Celtic Minstrel, xzKinGzxBuRnzx]
commands:
  magiccarpet:
    description: Take yourself wonder by wonder on a carpet made of glass.
    aliases: [mc]
    usage: /<command>
permissions:
  magiccarpet.mc:
    description: Take yourself wonder by wonder on a carpet made of glass.
    default: op